version: "3"

services:
  api:
    build: ./app
    ports:
      - 8080:8080

    volumes:
      - ./app:/app
    restart: always
    # depends_on:
    #     - db

  # db:
  #     image: postgres:13.0-alpine
  #     ports:
  #         - 5432:5432
  #     # volumes:
  #     # - postgres_data:/var/lib/postgresql/data/
  #     env_file:
  #     - ./app/.env
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
